language: java
jdk: openjdk6
install: cp pom.xml ./java && cd java && mvn package -DskipTests && cd -
script: sh ./build.sh
deploy:
  provider: releases
  api_key:
    secure: XqVfGi6CVDo2xIJJ4N2fMtDUuaH5Zhk381mRKCaC+yKpzF9fEUVgthIqmRWzLeskNx1nsLMgVz5YlTqmxTZvmHHsbt8fDZj55hVTmFJn8d+/79P/I9Nh6MJL5+5gJvGCk2gjU7VyPQr/Xg1Pxb5IJfNswuPOCuWSto8ZjaFDRSETXwFFnLGdIv0w5JgZMQq2AOG/jPgfmY1xPjsbMoUB2mgG8NDcuZMSRKmhFFczRpYBG1PCvhM4uvnkaRWFyasPqKLI9Kz/Mrehk+nS8EHwS7/5DVSfsOV8zT0tK4m08p9eYo7TA/WHcbeKjciqaiHzFx2Mo3MhFEPC1XIQ36ZUJXUTi/eB5ZhzQSsSpIVPkEgWq6U3ELZck1ZFAv48w8sjupL0/FbRezCKS37A7HnKWaROAHA/4QksR3VkqCcHDw416FST0+2h0QX+yst1aWJfxLrz7y1AM0tm1RWYQLJi3jn+uTfuojpw+TWug65cHrbgWllC4CU41pPjSpMwgqtximYLSEacDjBwtxxmSrPjz3I5P06HEZ1pLkRddTwI4FI3AsSNhuo+JRF1WEUwVzCUjVLwn2SJtblzFfoTJYGnl9ZeHFy0nsTyXX6R6tvAck+4tJpA3zZc9NAmNIWaH8t9MUj+9Zi3Ggl7jvqOyyIJoSbNPv3ttESkyl0okt0YZzg=
  file_glob: true
  file: ./target/RODPS*.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
